name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libs
      run: sudo apt update && sudo apt install -y libsfml-dev libcsfml-dev libsdl2-dev libsdl2-ttf-dev libncurses-dev
    - name: make
      run: make
